"""Render the deliverable tables (§12) from whatever results exist on disk.

    python -m src.report --table1
    python -m src.report --table2 --dataset cub
"""

from __future__ import annotations

import argparse
import json
from typing import Optional, Sequence

import numpy as np
import pandas as pd

from .paths import RESULTS_DIR


def table1() -> str:
    rows = []
    for p in sorted((RESULTS_DIR / "generative").glob("*.json")):
        d = json.loads(p.read_text())
        rows.append({
            "model": d["model"], "dataset": d["dataset"], "mode": d["mode"],
            # Without this the two generative rows per model are indistinguishable,
            # and the whole point of the pair is which question was asked.
            "question": d.get("question_key", "-" if d["mode"] == "zeroshot" else "default"),
            "strict": round(d["strict"], 2), "lenient": round(d["lenient"], 2),
            "%unmatched": round(d["pct_unmatched"], 2), "n": d["n"],
        })
    if not rows:
        return "_no generative results yet_\n"
    df = pd.DataFrame(rows).sort_values(["dataset", "mode", "model", "question"])
    md = ["# Table 1 — generative / zero-shot top-1 (§6.1)", "",
          "Three numbers per cell, never one: `strict` is matcher rungs 1-3 "
          "(normalise / exact / alias), `lenient` adds substring and embedding "
          "matching, and `%unmatched` is what the cascade could not resolve at all. "
          "Encoder rows are contrastive zero-shot, which has no matcher, so their "
          "strict and lenient columns are equal by construction.", ""]
    md.append(df.to_markdown(index=False))
    return "\n".join(md) + "\n"


def table2(dataset: Optional[str] = None) -> str:
    path = RESULTS_DIR / "table2_probes.csv"
    if not path.exists():
        return "_no probe results yet_\n"
    df = pd.read_csv(path)
    if dataset:
        df = df[df["dataset"] == dataset]
    df["key"] = df["tap"] + np.where(df["pooling"] == "-", "", "." + df["pooling"].astype(str))
    g = (df.groupby(["dataset", "model", "head", "key"])["top1"]
           .agg(["mean", "std", "count"]).reset_index())
    g["top1"] = g.apply(
        lambda r: f"{r['mean']:.2f}" + (f" ± {r['std']:.2f}" if r["count"] > 1 else ""), axis=1
    )
    wide = g.pivot_table(index=["dataset", "model", "head"], columns="key",
                         values="top1", aggfunc="first")
    order = [c for c in ["T0c", "T0.avg", "T0.cls", "T1.avg", "T1.final",
                         "T2.avg", "T2.final", "T3.avg", "T3.final",
                         "T3.pos0"] if c in wide.columns]
    rest = sorted(c for c in wide.columns if c not in order)
    wide = wide[order + rest]
    md = ["# Table 2 — linear-probe top-1 by tap (§6.2)", "",
          "Mean ± std over seeds where more than one seed was run. Widths differ "
          "between taps (1024 / 1152 / 4096 / 5120) and a wider linear probe is "
          "strictly more expressive, so a *higher* number at a wider tap is not by "
          "itself evidence of more information — see the PCA-matched control.", ""]
    md.append(wide.reset_index().to_markdown(index=False))
    return "\n".join(md) + "\n"


MODEL_ORDER = ["clip_l14_336", "siglip2_so400m", "llava15_7b", "llava15_13b",
               "lladav_8b", "lladav_8b_masked32"]
TAP_ORDER = ["T0c", "T0.avg", "T0.cls", "T1.avg", "T1.final", "T2.avg", "T2.final",
             "T3.avg", "T3.final", "T3.pos0", "Tmask.avg", "Tmask.first", "Tmask.last"]


def _order_models(present):
    return [m for m in MODEL_ORDER if m in present] + sorted(set(present) - set(MODEL_ORDER))


def _wide(df, value, keyfilter=None, order=TAP_ORDER):
    d = df if keyfilter is None else df[df["key"].map(keyfilter)]
    if d.empty:
        return None
    w = d.pivot_table(index="model", columns="key", values=value, aggfunc="first")
    cols = [c for c in order if c in w.columns] + sorted(c for c in w.columns if c not in order)
    w = w.reindex(_order_models(w.index))[cols]
    return w.round(2)


def appendix() -> str:
    """Every measured number, rendered from the CSVs so it cannot drift from them."""
    out = ["# Appendix — complete results", "",
           "Generated by `python -m src.report --appendix`; every value is read from "
           "`results/table2_probes.csv` and `results/table3_attributes.csv`. "
           "Single seed (0), `logreg` head, CUB test split unless noted.", ""]

    probes = pd.read_csv(RESULTS_DIR / "table2_probes.csv")
    probes["key"] = probes["tap"] + np.where(
        probes["pooling"] == "-", "", "." + probes["pooling"].astype(str))
    cub = probes[probes["dataset"] == "cub"]

    out += ["## A1. Class probe, top-1 (CUB, 200 classes, chance 0.5%)", ""]
    w = _wide(cub, "top1", keyfilter=lambda k: not k.startswith("mid."))
    out += [w.to_markdown(), "",
            "`T0c` is the contrastive embedding and exists only for the bare encoders. "
            "`T0.cls` is the ViT CLS token, which LLaVA drops; for SigLIP2 there is no "
            "CLS position at all, and for LLaDA-V the value shown is the patch mean. "
            "`Tmask.*` exists only in masked mode.", ""]

    out += ["## A2. Class probe, top-5", ""]
    w5 = _wide(cub, "top5", keyfilter=lambda k: not k.startswith("mid."))
    out += [w5.to_markdown(), ""]

    sweep = cub[cub["key"].str.startswith("mid.")]
    if not sweep.empty:
        out += ["## A3. Layer sweep (LLaVA-1.5-7B, CUB) — both poolings", "",
                "Layer 0 is the projected image embedding spliced into the sequence; "
                "layer 32 is the last LLM layer. `mid.L0.avg` = `T1.avg` and "
                "`mid.L32.avg` = `T2.avg` exactly, which is the free consistency check.", ""]
        d = sweep.copy()
        d["layer"] = d["key"].str.extract(r"mid\.L(\d+)\.").astype(int)
        d["pool"] = d["key"].str.rsplit(".", n=1).str[-1]
        t = d.pivot_table(index="layer", columns="pool", values="top1", aggfunc="first").round(2)
        out += [t.to_markdown(), ""]

    attrs = pd.read_csv(RESULTS_DIR / "table3_attributes.csv")
    a = attrs.rename(columns={"key": "key"})
    out += ["## A4. Attribute probe — mean AP over 269 CUB attributes", "",
            f"Prior (a probe that has learned nothing) = **{a['prior_AP'].iloc[0]:.2f}**. "
            "Read the lift in A5, not the raw mAP.", ""]
    out += [_wide(a, "mAP").to_markdown(), ""]
    out += ["## A5. Attribute probe — lift over prior", "",
            "The honest range for this experiment is 0 to ~26; the ceiling is CLIP-L's "
            "contrastive embedding. `T3.pos0` at +0.01 is the negative control: on a "
            "constant vector the probe recovers exactly the marginal.", ""]
    out += [_wide(a, "lift").to_markdown(), ""]

    imagenet = probes[probes["dataset"] != "cub"]
    if not imagenet.empty:
        out += ["## A6. ImageNet-val (1000 classes, 40k train / 10k test carve)", ""]
        out += [imagenet[["model", "dataset", "key", "d", "top1", "top5"]]
                .round(2).to_markdown(index=False), ""]
    return "\n".join(out) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--table1", action="store_true")
    p.add_argument("--table2", action="store_true")
    p.add_argument("--dataset", default=None)
    p.add_argument("--appendix", action="store_true",
                   help="every measured number, rendered from the CSVs")
    args = p.parse_args(argv)

    if args.appendix:
        out = RESULTS_DIR / "appendix.md"
        out.write_text(appendix())
        print(appendix())
        print(f"-> {out}")
        return
    if args.table1 or not (args.table1 or args.table2):
        out = RESULTS_DIR / "table1_generative.md"
        out.write_text(table1())
        print(table1())
        print(f"-> {out}")
    if args.table2:
        out = RESULTS_DIR / "table2_probes.md"
        out.write_text(table2(args.dataset))
        print(table2(args.dataset))
        print(f"-> {out}")


if __name__ == "__main__":
    main()
